### ISSUE TITLE
[Feature request] Thêm tính năng

### ISSUE THREAD

**Issue by AZZ-vopp** [AikoPanel/AikoPanel#10]
Thêm tính năng hiển thị số người đã mời từ 1 acc
thêm tính năng tính số người còn hsd ở gói đó và tổng số người mua gói
thêm nút bật tắt thông tin trên app ví dụ id mail gói hsd
cảm ơn aiko nhiều

**Comment by Github-Aiko** [comment]
Cái này để mình xem nhé

**Comment by Github-Aiko** [comment]
Còn cái 1 chưa xong nhé :D mình sẽ làm sau :D mấy cái đưới đã update dev

**Comment by Github-Aiko** [comment]
#31
