### ISSUE TITLE
chỉnh lại 

### ISSUE THREAD

**Issue by AZZ-vopp** [AikoPanel/AikoPanel#18]
chỗ hoa hồng trên web lên để 1.000 thay vì 1000.00

**Comment by Github-Aiko** [comment]
Cho xin image lại nha bạn

**Comment by AZZ-vopp** [comment]
![image](https://github.com/AikoPanel/AikoPanel/assets/64297334/130263b1-3eca-40a4-9b69-7bfce345a381)

**Comment by Github-Aiko** [comment]
#24 Fixed
