### ISSUE TITLE
[Feature request] bấm xem thông tin người dùng trong 1 máy chủ

### ISSUE THREAD

**Issue by trantuan668** [AikoPanel/AikoPanel#28]
Bạn thêm cái này vào nữa nhé , vì muốn biết danh sách người dùng đang dùng trong máy chủ đó là những người nào ấy. Khi bấm vào biểu tượng hình người.

![Capture](https://github.com/AikoPanel/AikoPanel/assets/14367442/d14f6a4c-7022-4262-894e-d659bde7192b)

**Comment by Github-Aiko** [comment]
Cái này Xflash có ấy bạn cấu trúc bên mình khác nên mình sẽ không update chức năng này nhé , nặng DB
