### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by GenzPN** [AikoPanel/AikoPanel#49]
Hãy mô tả chi tiết những vấn đề hoặc nhu cầu bạn gặp phải.

Thêm phương thức đặt lại dữ liệu gb trong bảng user

Ví dụ khách yêu cầu muốn tạo gói cá nhân

Gói VPN 1TB nhưng không có hạn sử dụng nào hết gb thì thôi

Không có bán công khai phục vụ 1 mình khách

![image](https://github.com/AikoPanel/AikoPanel/assets/39546317/43b2f298-3052-44b0-af51-8002e5f393f7)

**Comment by Github-Aiko** [comment]
#50

**Comment by Github-Aiko** [comment]
#50
