### ISSUE TITLE
[Feature request] 1 tài khoản mua nhiều gói khác nhau

### ISSUE THREAD

**Issue by trantuan668** [AikoPanel/AikoPanel#52]
Bạn có thể làm 1 tài khoản mua nhiều gói khác nhau và đường link token mỗi gói khác nhau để thuận tiện cho việc chia sẻ cho mỗi nhu cầu của khách nhé.

**Comment by Github-Aiko** [comment]
Mình sẽ không làm nhé có web cộng tác viên để làm gì thế bạn ?

**Comment by trantuan668** [comment]
thứ nhất cái này là người ta mua hộ cho người thân hoặc bạn bè mà không cần tạo thêm tài khoản.
Thứ 2 là mình k có ctv mà có thì ngta cũng muốn làm web con thôi.

**Comment by Github-Aiko** [comment]
Về cơ bản thêm 1 mail cũng không vấn đề gì ? nó khó quản lý hơn chứ ko thấy tiện ở đâu cả

**Comment by Github-Aiko** [comment]
Với cả cơ năng giới hạn thiết bị 1 số thứ nữa cũng không thể giải quyết đưicj vấn đề đó info và cách get ntn ?
