### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by danghoang1** [AikoPanel/AikoPanel#60]
🙇‍♂️🙇‍♂️🙇‍♂️Lưu ý: Các vấn đề không liên quan đến AikoPanel thì không giải đáp

Số phiên bản AikoPanel bạn đang sử dụng
--------

Mô tả ngắn gọn vấn đề bạn đang gặp phải
--------

Ảnh chụp màn hình của lỗi được báo cáo (Please do desensitization)
--------

Các tệp nhật ký mới nhất trong thư mục lưu trữ/nhật ký báo cáo từ #1 (Please do desensitization)
storage/logs
--------

**Comment by Github-Aiko** [comment]
What ?
