### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ownerskill** [AikoPanel/AikoPanel#63]
Lỗi ấn chữ Trang chủ quay về web mẹ 

![Screenshot (431)](https://github.com/AikoPanel/AikoPanel/assets/147895379/232b1d7f-9a7b-47c3-8403-c514d8b7f53c)

**Comment by Github-Aiko** [comment]
Theo logic code sẽ không bị nhé check lại domain + phiên bản sử dụng , lần sau commit bug thì nhớ thêm version nữa nhé

**Comment by Github-Aiko** [comment]
#62 Fix lỗi cá nhân hoá
