### ISSUE TITLE
[Feature request] thêm tính năng pay ở ctv

### ISSUE THREAD

**Issue by AZZ-vopp** [AikoPanel/AikoPanel#64]
làm lại trang pay config theo miền web ctv không trùng với web mẹ

**Comment by Github-Aiko** [comment]
Cái này thì set từ source pay nhé kaka

**Comment by Github-Aiko** [comment]
Cái này vẫn chờ sỹ kaka

**Comment by Github-Aiko** [comment]
#62 Đã update pay ở đây nha
