### ISSUE TITLE
UPDATE TÍNH NĂNG ID APPLE

### ISSUE THREAD

**Issue by thangvatri147** [AikoPanel/AikoPanel#67]
UPDATE TÍNH NĂNG KHÁCH NHẬN LƯỢT ID APPLE SẼ CÓ THÔNG BÁO VỀ BOT
VÀ KHI BỊ HẾT LƯỢT NHẬN ID APPLE SẼ CÓ THÊM NÚT RESET LƯỢT NHẬN ID APPLE

**Comment by Github-Aiko** [comment]
Để làm gì ?  sao ko để unlimit ?
